--- #YAML:1.0
name:               Wx-ActiveX
version:            0.16
abstract:           ActiveX Control Interface for Wx
author:
    - Graciliano M. P
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Wx:  0.57
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
